import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from '@/components/Banner'
import Navbar from '@/components/Navbar'
import FlipCountdown from '@rumess/react-flip-countdown'
import banner_girl from '../images/banner_girl.gif';
import asset7 from '../images/assets/asset 7.webp';
import asset8 from '../images/assets/asset 8.webp';
import asset9 from '../images/assets/asset 9.webp';
import asset10 from '../images/assets/asset 10.webp';
import asset11 from '../images/assets/asset 11.webp';
import asset36 from '../images/assets/asset 36.png';
import banner_img1 from '../images/banner_img1.webp';
import banner_img2 from '../images/banner_img2.webp';
import banner_img3 from '../images/banner_img3.webp';
import banner_img4 from '../images/banner_img4.webp';
import banner_img5 from '../images/banner_img5.webp';
import banner_img6 from '../images/banner_img6.webp';
import card_one from '../images/card_one.webp';
import Card from '@/components/Card'
import React, { useEffect, useState } from 'react'
import RoundSlider from '@/components/RoundSlider'
import RoundSlider2 from '@/components/RoundSlider2'
import RoundSlide3 from '@/components/RoundSlide3'
import after_pay from '../images/after_pay.webp';
import klarna from '../images/klarna.webp'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [show, setShow] = useState(true);
  const [lastScrollY, setLastScrollY] = useState(0);

  const controlNavbar = () => {
    console.log(window.scrollY)
    if (typeof window !== 'undefined') {
      if (window.scrollY == '0') {
        setShow(false);
        setLastScrollY(0);
        return;
      }
      if (window.scrollY > lastScrollY) { // if scroll down hide the navbar
        setShow(true);
      } else { // if scroll up show the navbar
        setShow(false);
      }

      // remember current page location to use in the next move
      setLastScrollY(window.scrollY);
    }
  };

  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.addEventListener('scroll', controlNavbar);

      // cleanup function
      return () => {
        window.removeEventListener('scroll', controlNavbar);
      };
    }
  }, [lastScrollY]);

  return (
    <>
      <Head>
        <title>Temu | Explore the Latest Clothing, Beauty, Home, Jewelery & More</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/temu.svg" />
      </Head>
      <div>


        <nav className={`active ${show && 'hidden'}`}>
          <div className='bg-black'>
            <Banner />
          </div>
          <div className='bg-[#859f49] opacity-[0.98]'>
            <Navbar />
          </div>

        </nav>


        <div className='pt-[126px]'>
          <Image src={banner_girl} />
        </div>

        <div className='px-[44px] mx-[44px] mt-6 h-[48px] '>
          <div className=' flex justify-between px-3 py-2 hover:bg-[#dfdddd] bg-[#f0f0f0]'>
            <div className='flex gap-10'>
              <div className='flex gap-1 text-[16px] text-black font-[500] items-center'>
                <Image src={asset7} className='w-[28px]' />
                <div>Safe payments</div>
              </div>

              <div className='flex gap-2 text-[16px] text-black font-[500] items-center'>
                <Image src={asset8} className='w-[28px]' />
                <div>Secure logistics</div>
              </div>

              <div className='flex gap-2 text-[16px] text-black font-[500] items-center'>
                <Image src={asset9} className='w-[28px]' />
                <div>Secure privacy</div>
              </div>

              <div className='flex gap-2 text-[16px] text-black font-[500] items-center'>
                <Image src={asset10} className='w-[28px]' />
                <div>Purchase protection</div>
              </div>
            </div>
            <div>
              <div className='flex text-[16px] text-black font-[500] items-center'>
                <div>Temu keeps you safe</div>
                <Image src={asset11} className='w-[28px]' />
              </div>
            </div>
          </div>
        </div>


        <div className='px-[44px] mx-[44px] mt-6'>
          <div className={styles.flower}>
            <div>
              <div className='flex text-[16px] gap-1 text-black font-[500] items-center'>
                <Image src={asset36} className='w-[24px]' />
                <div className='text-[24px] text-white font-[800] italic leading-[1.5rem] mr-3'>Lightning deals</div>
                <div className='text-[16px] text-white font-[500]  leading-[1.5rem] '>Ends in</div>
                <FlipCountdown
                  theme={'light'}
                  size='extra-small'
                  hideYear
                  hideMonth
                  hideDay
                  hourTitle=' '
                  minuteTitle=' '
                  secondTitle={' '}
                  endAt={'2023-3-28 22:26:58'} // Date/Time
                />
                <Image src={asset11} className='w-[16px]' />
              </div>
            </div>

          </div>
        </div>

        <div className="grid grid-cols-5 gap-5 px-[44px] mx-[44px] mt-6">
          <Image src={card_one} className='w-72 border border-orange-500 rounded-md hover:bg-[#f0f0f0]' />
          <Card />
          <Card />
          <Card />
          <Card />
        </div>

        <div className="grid grid-cols-5 gap-5 px-[44px] mx-[44px] mt-6 mb-4">
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
        </div>

        <div className="grid grid-cols-3 gap-5 px-[44px] mx-[44px] mt-16 mb-4">
          <div className='overflow-hidden'>
            <Image src={banner_img1} className='hover:scale-[1.05] transition-all' />
          </div>
          <div className='overflow-hidden'>
            <Image src={banner_img2} className='hover:scale-[1.05] transition-all' />
          </div>
          <div className='overflow-hidden'>
            <Image src={banner_img3} className='hover:scale-[1.05] transition-all' />
          </div>
        </div>

        <div className="grid grid-cols-2 gap-5 px-[44px] mx-[44px] mt-16 mb-4">
          <div className='overflow-hidden'>
            <Image src={banner_img4} className='hover:scale-[1.05] transition-all' />
          </div>
          <div className='overflow-hidden'>
            <Image src={banner_img5} className='hover:scale-[1.05] transition-all' />
          </div>
        </div>

        <div className='px-[24px] mx-[24px] mt-8 mb-4'>
          <RoundSlider />
        </div>

        <div className='px-[24px] mx-[24px] mt-10 mb-4'>
          <RoundSlider2 />
        </div>

        <div className='px-[24px] mx-[24px] mt-10 mb-4'>
          <RoundSlide3 />
        </div>

        <div className='px-[44px] mx-[44px] mt-6 mb-6'>
          <div className={styles.flower}>
            <div>
              <div className='flex text-[16px] gap-1 text-black font-[500] items-center'>
                {/* <div className='text-[24px] text-white font-[800] italic leading-[1.5rem] mr-3'>Shop now, pay later with</div> */}
                <Image src={after_pay} className='h-[48px] w-[713px] scale-[0.70]' />
                {/* <div className='text-[16px] text-white font-[500]  leading-[1.5rem] '>or</div>
                <Image src={klarna} className='' /> */}
              </div>
            </div>

          </div>
        </div>

      </div>
    </>
  )
}
