import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from '@/components/Banner'
import Navbar from '@/components/Navbar'
import FlipCountdown from '@rumess/react-flip-countdown'
import banner_girl from '../images/banner_girl.gif';
import asset7 from '../images/assets/asset 7.webp';
import asset8 from '../images/assets/asset 8.webp';
import asset9 from '../images/assets/asset 9.webp';
import asset10 from '../images/assets/asset 10.webp';
import asset11 from '../images/assets/asset 11.webp';
import asset36 from '../images/assets/asset 36.png';
import banner_img1 from '../images/banner_img1.webp';
import banner_img2 from '../images/banner_img2.webp';
import banner_img3 from '../images/banner_img3.webp';
import banner_img4 from '../images/banner_img4.webp';
import banner_img5 from '../images/banner_img5.webp';
import banner_img6 from '../images/banner_img6.webp';
import card_one from '../images/card_one.webp';
import Card from '@/components/Card'
import Card5 from '@/components/Card5';
import React, { useEffect, useState } from 'react'
import RoundSlider from '@/components/RoundSlider'
import RoundSlider2 from '@/components/RoundSlider2'
import RoundSlide3 from '@/components/RoundSlide3'
import RoundSlide4 from '@/components/RoundSlide4'
import after_pay from '../images/after_pay.webp';
import klarna from '../images/klarna.webp'
import Footer from '@/components/Footer'
import RoundSlide5 from '../components/RoundSlide5';
import RoundSlide6 from '../components/RoundSlide6';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [show, setShow] = useState(false);
  const [lastScrollY, setLastScrollY] = useState(0);

  const controlNavbar = () => {
    console.log(window.scrollY)
    if (typeof window !== 'undefined' || true) {
      if (window.scrollY == '0') {
        setShow(false);
        setLastScrollY(0);
        return;
      }
      if (window.scrollY > lastScrollY) { // if scroll down hide the navbar
        setShow(true);
      } else { // if scroll up show the navbar
        setShow(false);
      }

      // remember current page location to use in the next move
      setLastScrollY(window.scrollY);
    }
  };

  useEffect(() => {
    if (typeof window !== 'undefined' || true) {
      window.addEventListener('scroll', controlNavbar);

      // cleanup function
      return () => {
        window.removeEventListener('scroll', controlNavbar);
      };
    }
  }, [lastScrollY]);

  return (
    <>
      <Head>
        <title>Temu | Explore the Latest Clothing, Beauty, Home, Jewelery & More</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/temu.svg" />
      </Head>
      <div>


        <nav className={`active ${show && 'hidden'}`}>
          <div className='border border-gray-800 bg-orange-600'>
            <Banner />
          </div>
          <div className='bg-orange-600 opacity-[0.98]'>
            <Navbar />
          </div>

        </nav>


        <div className='pt-[140px]'>
          <Image src={banner_girl} className='w-full' />
        </div>

        <div className='  h-[48px] '>
          <div className='  px-3 py-2 hover:bg-[#dfdddd] bg-[#f0f0f0]'>
            <div className='flex gap-10 justify-around'>
              <div className='flex gap-1 text-[16px] text-black font-[500] items-center'>
                {/* <Image src={asset7} className='w-[28px]' /> */}
                <button className='px-4 py-1 border border-gray-800 rounded-md hover:bg-gray-400'>New Arrivals</button>
              </div>

              <div className='flex gap-2 text-[16px] text-black font-[500] items-center'>
                {/* <Image src={asset8} className='w-[28px]' /> */}
                <button className='px-4 py-1 border border-gray-800 rounded-md hover:bg-gray-400'>Big Sales</button>
              </div>

              <div className='flex gap-2 text-[16px] text-black font-[500] items-center'>
                {/* <Image src={asset9} className='w-[28px]' /> */}
                <button className='px-4 py-1 border border-gray-800 rounded-md hover:bg-gray-400'>Best Seller</button>
              </div>

              <div className='flex gap-2 text-[16px] text-black font-[500] items-center'>
                {/* <Image src={asset10} className='w-[28px]' /> */}
                <button className='px-4 py-1 border border-gray-800 rounded-md hover:bg-gray-400'>Premium</button>
              </div>
            </div>
            {/* <div>
              <div className='flex text-[16px] text-black font-[500] items-center'>
                <div>Temu keeps you safe</div>
                <Image src={asset11} className='w-[28px]' />
              </div>
            </div> */}
          </div>
        </div>


        {/* <div className='px-[44px] mx-[44px] mt-6'>
          <div className={styles.flower}>
            <div>
              <div className='flex text-[16px] gap-1 text-black font-[500] items-center'>
                <Image src={asset36} className='w-[24px]' />
                <div className='text-[24px] text-white font-[800] italic leading-[1.5rem] mr-3'>Lightning deals</div>
                <div className='text-[16px] text-white font-[500]  leading-[1.5rem] '>Ends in</div>
                <FlipCountdown
                  theme={'light'}
                  size='extra-small'
                  hideYear
                  hideMonth
                  hideDay
                  hourTitle=' '
                  minuteTitle=' '
                  secondTitle={' '}
                  endAt={'2023-3-30 22:26:58'} // Date/Time
                />
                <Image src={asset11} className='w-[16px]' />
              </div>
            </div>

          </div>
        </div> */}

        <div className="  px-[25px] mx-[25px] mt-6">
          {/* <Image src={card_one} className='w-72 border border-orange-500 rounded-md hover:bg-[#f0f0f0]' /> */}
          <RoundSlide5 />
        </div>

        <div className="  px-[25px] mx-[25px] mt-6">
          {/* <Image src={card_one} className='w-72 border border-orange-500 rounded-md hover:bg-[#f0f0f0]' /> */}
          <RoundSlide6 />
        </div>

        <div className="grid grid-cols-3 gap-5 px-[44px] mx-[44px] mt-16 mb-4">
          <div className='overflow-hidden'>
            <Image src={banner_img1} className='hover:scale-[1.05] transition-all' />
          </div>
          <div className='overflow-hidden'>
            <Image src={banner_img2} className='hover:scale-[1.05] transition-all' />
          </div>
          <div className='overflow-hidden'>
            <Image src={banner_img3} className='hover:scale-[1.05] transition-all' />
          </div>
        </div>

        <div className="grid grid-cols-2 gap-5 px-[44px] mx-[44px] mt-16 mb-4">
          <div className='overflow-hidden'>
            <Image src={banner_img4} className='hover:scale-[1.05] transition-all' />
          </div>
          <div className='overflow-hidden'>
            <Image src={banner_img5} className='hover:scale-[1.05] transition-all' />
          </div>
        </div>

        <div className='px-[24px] mx-[24px] mt-8 mb-4'>
          <RoundSlider />
        </div>

        <div className='px-[24px] mx-[24px] mt-10 mb-4'>
          <RoundSlider2 />
        </div>

        <div className='px-[24px] mx-[24px] mt-10 mb-4'>
          <RoundSlide3 />
        </div>

        <div className='px-[44px] mx-[44px] mt-6 mb-6'>
          <div className={styles.flower}>
            <div>
              <div className='flex text-[16px] gap-1 text-black font-[500] items-center'>
                {/* <div className='text-[24px] text-white font-[800] italic leading-[1.5rem] mr-3'>Shop now, pay later with</div> */}
                <Image src={after_pay} className='h-[48px] w-[713px] scale-[0.70]' />
                {/* <div className='text-[16px] text-white font-[500]  leading-[1.5rem] '>or</div>
                <Image src={klarna} className='' /> */}
              </div>
            </div>
          </div>
        </div>

        <div className='px-[24px] mx-[24px] mt-10 mb-4'>
          <RoundSlide4 />
          <div className="grid grid-cols-5 mx-[20px] gap-1">
            <Card5 /> <Card5 /> <Card5 /> <Card5 /> <Card5 />
            <Card5 /> <Card5 /> <Card5 /> <Card5 /> <Card5 />
            <Card5 /> <Card5 /> <Card5 /> <Card5 /> <Card5 />
            <Card5 /> <Card5 /> <Card5 /> <Card5 /> <Card5 />
            <Card5 /> <Card5 /> <Card5 /> <Card5 /> <Card5 />
            <Card5 /> <Card5 /> <Card5 /> <Card5 /> <Card5 />
            <Card5 /> <Card5 /> <Card5 /> <Card5 /> <Card5 />
            <Card5 /> <Card5 /> <Card5 /> <Card5 /> <Card5 />
          </div>

          <div className="flex justify-center items-center mt-[38px] mb-[70px]">
            <div className='flex justify-center items-center cursor-pointer 
            gap-2 w-[220px] h-[52px] border border-gray-800 rounded-full hover:shadow-xl'>
              <div>View more</div>
              <div>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" 
                className="w-4 h-4 mt-1">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
                </svg>
              </div>
            </div>
          </div>
        </div>

        <Footer />

      </div>
    </>
  )
}
